apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo2.fullname" . }}-config
  labels:
    {{- include "demo2.labels" . | nindent 4 }}
data:
  redis.conf: |
{{ .Values.configMap.redisConfig | indent 4 }}
